# Generated by Django 4.2 on 2023-04-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Shoe name')),
                ('price', models.PositiveIntegerField(verbose_name='Shoe price')),
                ('img', models.ImageField(upload_to='home', verbose_name='Shoe image')),
                ('video', models.FileField(upload_to='', verbose_name='Shoe video')),
            ],
        ),
    ]
